/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbankmanagements;

/**
 *
 * @author wahid
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adddonor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        updatedonor = new javax.swing.JButton();
        searchdonor = new javax.swing.JButton();
        removedonor = new javax.swing.JButton();
        alldonors = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adddonor.setBackground(new java.awt.Color(255, 0, 0));
        adddonor.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        adddonor.setForeground(new java.awt.Color(255, 255, 255));
        adddonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add new.png"))); // NOI18N
        adddonor.setText("Add Donor");
        adddonor.setPreferredSize(new java.awt.Dimension(160, 40));
        adddonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddonorActionPerformed(evt);
            }
        });
        getContentPane().add(adddonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 513, 50));

        jLabel1.setFont(new java.awt.Font("Lato Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Blood Bank Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 496, -1));

        updatedonor.setBackground(new java.awt.Color(255, 0, 0));
        updatedonor.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        updatedonor.setForeground(new java.awt.Color(255, 255, 255));
        updatedonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update details.png"))); // NOI18N
        updatedonor.setText("Update Donor Data");
        updatedonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedonorActionPerformed(evt);
            }
        });
        getContentPane().add(updatedonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 513, -1));

        searchdonor.setBackground(new java.awt.Color(255, 0, 0));
        searchdonor.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        searchdonor.setForeground(new java.awt.Color(255, 255, 255));
        searchdonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search1.png"))); // NOI18N
        searchdonor.setText("Search Donor");
        searchdonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdonorActionPerformed(evt);
            }
        });
        getContentPane().add(searchdonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 513, -1));

        removedonor.setBackground(new java.awt.Color(255, 0, 0));
        removedonor.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        removedonor.setForeground(new java.awt.Color(255, 255, 255));
        removedonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        removedonor.setText("Remove Donor");
        removedonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removedonorActionPerformed(evt);
            }
        });
        getContentPane().add(removedonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 513, -1));

        alldonors.setBackground(new java.awt.Color(255, 0, 0));
        alldonors.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        alldonors.setForeground(new java.awt.Color(255, 255, 255));
        alldonors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Details.png"))); // NOI18N
        alldonors.setText("See All Donor");
        alldonors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alldonorsActionPerformed(evt);
            }
        });
        getContentPane().add(alldonors, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 513, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, -10, 680, 520));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 680, 230));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 690, 540));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 690, 230));

        jMenuBar2.setBackground(new java.awt.Color(102, 0, 51));
        jMenuBar2.setForeground(new java.awt.Color(255, 255, 255));

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adddonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddonorActionPerformed
                                                         
        // TODO add your handling code here:
        setVisible(false);
        AddDonor add=new AddDonor();
        add.setVisible(true);
    }//GEN-LAST:event_adddonorActionPerformed

    private void updatedonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedonorActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        UpdateDonor update=new UpdateDonor();
        update.setVisible(true);
    }//GEN-LAST:event_updatedonorActionPerformed

    private void searchdonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdonorActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        SearchDonor sr=new SearchDonor();
        sr.setVisible(true);
    }//GEN-LAST:event_searchdonorActionPerformed

    private void removedonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removedonorActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        RemoveDonor rm=new RemoveDonor();
        rm.setVisible(true);
    }//GEN-LAST:event_removedonorActionPerformed

    private void alldonorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alldonorsActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        AllDonorList alld=new AllDonorList();
        alld.setVisible(true);
    }//GEN-LAST:event_alldonorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddonor;
    private javax.swing.JButton alldonors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JButton removedonor;
    private javax.swing.JButton searchdonor;
    private javax.swing.JButton updatedonor;
    // End of variables declaration//GEN-END:variables
}
