/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbankmanagements;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author wahid
 */
public class RemoveDonor extends javax.swing.JFrame {

    /**
     * Creates new form RemoveDonor
     */
    public RemoveDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iddonor = new javax.swing.JLabel();
        Homepage = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bloodgrp = new javax.swing.JLabel();
        lastblood = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        adress = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        donoremail = new javax.swing.JLabel();
        donorname = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        searchdonorbtn = new javax.swing.JButton();
        searchbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Removedonor = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        donorid = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iddonor.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        iddonor.setText("null");
        getContentPane().add(iddonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 150, -1));

        Homepage.setBackground(new java.awt.Color(0, 51, 51));
        Homepage.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        Homepage.setForeground(new java.awt.Color(255, 255, 255));
        Homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout.png"))); // NOI18N
        Homepage.setText("Back To Home Page");
        Homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomepageActionPerformed(evt);
            }
        });
        getContentPane().add(Homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, -1, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setText("Donor Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 172, -1, 43));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setText("Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 221, 82, 43));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 270, -1, 43));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setText("Phone No:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 319, 133, 43));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setText("Adress:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 368, 101, 43));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel8.setText("Date of Birth:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 417, 169, 43));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel9.setText("Last Blood Donated Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 466, 313, 43));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel7.setText("Blood Group:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 511, 169, 43));

        bloodgrp.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(bloodgrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 518, 174, -1));

        lastblood.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(lastblood, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 473, 174, -1));

        dob.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 424, 174, -1));

        adress.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 375, 174, -1));

        phone.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 326, 174, -1));

        donoremail.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(donoremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 267, 510, 40));

        donorname.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(donorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 228, 174, -1));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 179, 781, -1));

        searchdonorbtn.setBackground(new java.awt.Color(102, 0, 0));
        searchdonorbtn.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        searchdonorbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchdonorbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search1.png"))); // NOI18N
        searchdonorbtn.setText("Search Donor");
        searchdonorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdonorbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchdonorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 90, -1, -1));

        searchbox.setBackground(new java.awt.Color(255, 51, 0));
        searchbox.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        searchbox.setForeground(new java.awt.Color(255, 255, 255));
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        getContentPane().add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 90, 466, -1));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Remove Donor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 22, -1, -1));

        Removedonor.setBackground(new java.awt.Color(102, 0, 0));
        Removedonor.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        Removedonor.setForeground(new java.awt.Color(255, 255, 255));
        Removedonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        Removedonor.setText("Remove Donor");
        Removedonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovedonorActionPerformed(evt);
            }
        });
        getContentPane().add(Removedonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 293, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        donorid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        getContentPane().add(donorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

        jMenu1.setText("File");

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomepageActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        HomePage hm = new HomePage();
        hm.setVisible(true);
    }//GEN-LAST:event_HomepageActionPerformed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void searchdonorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdonorbtnActionPerformed
        // TODO add your handling code here:
        String searchmail = searchbox.getText();
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Diu_projects", "wahid", "Wahid@#81");
            Statement st = connection.createStatement();

            ResultSet rt = st.executeQuery("select * from donor where email='" + searchmail + "'");
            if (rt.next()) {
                iddonor.setText(rt.getString(1));
                donoremail.setText(rt.getString(3));
                phone.setText(rt.getString(4));
                bloodgrp.setText(rt.getString(8));
                adress.setText(rt.getString(5));

                dob.setText(rt.getString(9));
                lastblood.setText(rt.getString(10));
                donorname.setText(rt.getString(2));

            } else {
                JOptionPane.showMessageDialog(null, "Donor not found");

            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchdonorbtnActionPerformed

    private void RemovedonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovedonorActionPerformed
        String searchmail = searchbox.getText();
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Diu_projects", "wahid", "Wahid@#81");
            Statement st = connection.createStatement();
            st.executeUpdate("delete from donor where email='"+searchmail+"'");
            JOptionPane.showMessageDialog(null, "Donor Removed sucessfully!");
            setVisible(false);
            new RemoveDonor().setVisible(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_RemovedonorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Homepage;
    private javax.swing.JButton Removedonor;
    private javax.swing.JLabel adress;
    private javax.swing.JLabel bloodgrp;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel donoremail;
    private javax.swing.JLabel donorid;
    private javax.swing.JLabel donorname;
    private javax.swing.JLabel iddonor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lastblood;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchdonorbtn;
    // End of variables declaration//GEN-END:variables
}
