/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodbankmanagements;

/**
 *
 * @author wahid
 */
public class Spalshscreen extends javax.swing.JFrame {

    /**
     * Creates new form Spalshscreen
     */
    public Spalshscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numbr = new javax.swing.JLabel();
        pgbar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1326, 607, -1, -1));

        numbr.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numbr.setForeground(new java.awt.Color(255, 255, 255));
        numbr.setText("0%");
        getContentPane().add(numbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, -1, -1));

        pgbar.setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().add(pgbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 510, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1911.i029.021_realistic blood donor horizontal poster.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spalshscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spalshscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spalshscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spalshscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Spalshscreen sp=new Spalshscreen();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             sp.setVisible(true);
            }
        });
        
        
        Login lg=new Login();
        
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(20);
                sp.pgbar.setValue(i);
                sp.numbr.setText(Integer.toString(i)+"%");
                
            }
        }
        catch(Exception e){
        }
        
        new Spalshscreen().setVisible(false);
        lg.setVisible(true);
        sp.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel numbr;
    private javax.swing.JProgressBar pgbar;
    // End of variables declaration//GEN-END:variables
}
